# path to the directory containing setup.py relative to the environment file
-e ..https://github.com/jeradmelgard/HTM_CAPM
name: myenv
channels:
  - defaults
dependencies:
  - numpy=1.25.2
  - pandas=2.0.3
  - matplotlib=3.7.1
